services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_MXF_TO_EDL_URL: "http://backend_python:8000"
      NEXT_PUBLIC_MXF_TO_MP4_URL: "http://backend_csharp:8080"
    depends_on:
      - backend_python
      - backend_csharp
      - backend_csharp_worker
    networks:
      - backend

  backend_python:
    container_name: backend_python
    build:
      context: ./backend_python
    env_file: 
      - ./backend_python/.env
    volumes:
      - mxf-shared:/app/temp
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  backend_csharp:
    container_name: backend_csharp
    build:
      context: ./backend_c#
      dockerfile: API/Dockerfile
    user: root
    volumes:
      - mxf-shared:/app/temp
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AZUREBLOBACCOUNTNAME: mxftomp4
      AZUREBLOBACCOUNTKEY: "sua key aqui"
      AZUREBLOBCONTAINER: mp4-output
      CONNECTIONSTRINGSREDIS: redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - backend

  backend_csharp_worker:
    image: worker
    build:
      context: ./backend_c#
      dockerfile: Worker/Dockerfile
    user: root
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AZUREBLOBACCOUNTNAME: mxftomp4
      AZUREBLOBACCOUNTKEY: "sua key aqui"
      AZUREBLOBCONTAINER: mp4-output
      CONNECTIONSTRINGSREDIS: redis:6379
      WORKERTempFolder: /app/temp
      WORKERFfmpegPath: ffmpeg
      WORKERFfprobePath: ffprobe
      WORKERMaxDegreeOfParallelism: 2
      QUEUEProcessingQueueName: process-queue
      QUEUEPoisonQueueName: process-poison
      QUEUE__MaxDeliveryCount: 5
    volumes:
      - mxf-shared:/app/temp
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - backend

volumes:
  mxf-shared:
  redis-data:
  pgdata:

networks:
  backend:
